In [ ]:
!pip install pandas

In [1]:
import pandas as pd

In [85]:
df1 = pd.read_excel("F:\\Dataset\\25. Order.xlsx")

In [71]:
df.to_json("newfile.json")

In [6]:
type(df)

pandas.core.frame.DataFrame

In [70]:
df.head()

,orderID,customerID,employeeID,orderDate,requiredDate,shippedDate,shipVia,freight,shipName,shipAddress,shipCity,shipRegion,shipPostalCode,shipCountry
0,10248,VINET,5,1996-07-04 00:00:00,1996-08-01 00:00:00,1996-07-16,3,32.38,Vins et alcools Chevalier,59 rue de l'Abbaye,Reims,NaN,51100,France
1,10249,TOMSP,6,1996-07-05 00:00:00,1996-08-16 00:00:00,1996-07-10,1,11.61,Toms SpezialitÃ¤ten,Luisenstr. 48,MÃ¼nster,NaN,44087,Germany
2,10250,HANAR,4,1996-07-08 00:00:00,1996-08-05 00:00:00,1996-07-12,2,65.83,Hanari Carnes,Rua do PaÃ§o 67,Rio de Janeiro,RJ,05454-876,Brazil
3,10251,VICTE,3,1996-07-08 00:00:00,1996-08-05 00:00:00,1996-07-15,1,41.34,Victuailles en stock,2 rue du Commerce,Lyon,NaN,69004,France
4,10252,SUPRD,4,1996-07-09 00:00:00,1996-08-06 00:00:00,1996-07-11,2,51.30,SuprÃªmes dÃ©lices,Boulevard Tirou 255,Charleroi,NaN,B-6000,Belgium

In [8]:
df.shape

(838, 14)

In [9]:
df.size

11732

In [10]:
df.tail()

,orderID,customerID,employeeID,orderDate,requiredDate,shippedDate,shipVia,freight,shipName,shipAddress,shipCity,shipRegion,shipPostalCode,shipCountry
833,11073,PERIC,2,35920,35948,NaT,2,24.95,Pericles Comidas clÃ¡sicas,Calle Dr. Jorge Cash 321,MÃ©xico D.F.,NaN,5033,Mexico
834,11074,SIMOB,7,35921,35949,NaT,2,18.44,Simons bistro,VinbÃ¦ltet 34,Kobenhavn,NaN,1734,Denmark
835,11075,RICSU,8,35921,35949,NaT,2,6.19,Richter Supermarkt,Starenweg 5,GenÃ¨ve,NaN,1204,Switzerland
836,11076,BONAP,4,35921,35949,NaT,2,38.28,Bon app',12 rue des Bouchers,Marseille,NaN,13008,France
837,11077,RATTC,1,35921,35949,NaT,2,8.53,Rattlesnake Canyon Grocery,2817 Milton Dr.,Albuquerque,NM,87110,USA

In [17]:
df.sample(5)

,orderID,customerID,employeeID,orderDate,requiredDate,shippedDate,shipVia,freight,shipName,shipAddress,shipCity,shipRegion,shipPostalCode,shipCountry
139,10387,SANTG,1,1996-12-18 00:00:00,1997-01-15 00:00:00,1996-12-20,2,93.63,SantÃ© Gourmet,Erling Skakkes gate 78,Stavern,NaN,4110,Norway
337,10585,WELLI,7,1997-07-01 00:00:00,1997-07-29 00:00:00,1997-07-10,1,13.41,Wellington Importadora,Rua do Mercado 12,Resende,SP,08737-363,Brazil
505,10753,FRANS,3,1997-11-25 00:00:00,1997-12-23 00:00:00,1997-11-27,1,7.70,Franchi S.p.A.,Via Monte Bianco 34,Torino,NaN,10100,Italy
173,10421,QUEDE,8,1997-01-21 00:00:00,1997-03-04 00:00:00,1997-01-27,1,99.23,Que DelÃ­cia,Rua da Panificadora 12,Rio de Janeiro,RJ,02389-673,Brazil
121,10369,SPLIR,8,1996-12-02 00:00:00,1996-12-30 00:00:00,1996-12-09,2,195.68,Split Rail Beer & Ale,P.O. Box 555,Lander,WY,82520,USA

In [19]:
len(df.columns)

14

In [20]:
df.columns

Index(['orderID', 'customerID', 'employeeID', 'orderDate', 'requiredDate',
       'shippedDate', 'shipVia', 'freight', 'shipName', 'shipAddress',
       'shipCity', 'shipRegion', 'shipPostalCode', 'shipCountry'],
      dtype='object')

In [24]:
type(df.shipName)

pandas.core.series.Series

In [30]:
df[["shipRegion", "shipCountry", "customerID"]]

    shipRegion  shipCountry customerID
0          NaN       France      VINET
1          NaN      Germany      TOMSP
2           RJ       Brazil      HANAR
3          NaN       France      VICTE
4          NaN      Belgium      SUPRD
..         ...          ...        ...
833        NaN       Mexico      PERIC
834        NaN      Denmark      SIMOB
835        NaN  Switzerland      RICSU
836        NaN       France      BONAP
837         NM          USA      RATTC

[838 rows x 3 columns]

In [31]:
df.dtypes

orderID                    int64
customerID                object
employeeID                 int64
orderDate                 object
requiredDate              object
shippedDate       datetime64[ns]
shipVia                    int64
freight                  float64
shipName                  object
shipAddress               object
shipCity                  object
shipRegion                object
shipPostalCode            object
shipCountry               object
dtype: object

In [32]:
df.describe()

,orderID,employeeID,shippedDate,shipVia,freight
count,838.000000,838.000000,809,838.000000,838.000000
mean,10666.423628,4.396181,1997-08-09 23:45:45.611866368,2.004773,78.084308
min,10248.000000,1.000000,1996-07-10 00:00:00,1.000000,0.020000
25%,10457.250000,2.000000,1997-02-28 00:00:00,1.000000,13.332500
50%,10666.500000,4.000000,1997-09-09 00:00:00,2.000000,40.370000
75%,10875.750000,7.000000,1998-02-04 00:00:00,3.000000,91.430000
max,11077.000000,9.000000,1998-05-06 00:00:00,3.000000,1007.640000
std,241.924178,2.500769,NaN,0.777507,116.527350

In [34]:
df.describe(include="all").T

,count,unique,top,freq,mean,min,25%,50%,75%,max,std
orderID,838.0,NaN,NaN,NaN,10666.423628,10248.0,10457.25,10666.5,10875.75,11077.0,241.924178
customerID,838,89,SAVEA,31,NaN,NaN,NaN,NaN,NaN,NaN,NaN
employeeID,838.0,NaN,NaN,NaN,4.396181,1.0,2.0,4.0,7.0,9.0,2.500769
orderDate,838,482,1998-02-26 00:00:00,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
requiredDate,838,456,1998-03-26 00:00:00,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
shippedDate,809,NaN,NaN,NaN,1997-08-09 23:45:45.611866368,1996-07-10 00:00:00,1997-02-28 00:00:00,1997-09-09 00:00:00,1998-02-04 00:00:00,1998-05-06 00:00:00,NaN
shipVia,838.0,NaN,NaN,NaN,2.004773,1.0,1.0,2.0,3.0,3.0,0.777507
freight,838.0,NaN,NaN,NaN,78.084308,0.02,13.3325,40.37,91.43,1007.64,116.52735
shipName,838,90,Save-a-lot Markets,31,NaN,NaN,NaN,NaN,NaN,NaN,NaN
shipAddress,838,89,187 Suffolk Ln.,31,NaN,NaN,NaN,NaN,NaN,NaN,NaN
shipCity,838,70,Rio de Janeiro,34,NaN,NaN,NaN,NaN,NaN,NaN,NaN
shipRegion,325,19,SP,49,NaN,NaN,NaN,NaN,NaN,NaN,NaN
shipPostalCode,819.0,83.0,83720.0,31.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
shipCountry,838,21,USA,123,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [36]:
df.describe(include="O")

,customerID,orderDate,requiredDate,shipName,shipAddress,shipCity,shipRegion,shipPostalCode,shipCountry
count,838,838,838,838,838,838,325,819,838
unique,89,482,456,90,89,70,19,83,21
top,SAVEA,1998-02-26 00:00:00,1998-03-26 00:00:00,Save-a-lot Markets,187 Suffolk Ln.,Rio de Janeiro,SP,83720,USA
freq,31,6,7,31,31,34,49,31,123

In [40]:
df.drop(0,inplace=True)

In [45]:
df.drop("orderID", axis=1, inplace=True )

In [46]:
df

,customerID,employeeID,orderDate,requiredDate,shippedDate,shipVia,freight,shipName,shipAddress,shipCity,shipRegion,shipPostalCode,shipCountry
1,TOMSP,6,1996-07-05 00:00:00,1996-08-16 00:00:00,1996-07-10,1,11.61,Toms SpezialitÃ¤ten,Luisenstr. 48,MÃ¼nster,NaN,44087,Germany
2,HANAR,4,1996-07-08 00:00:00,1996-08-05 00:00:00,1996-07-12,2,65.83,Hanari Carnes,Rua do PaÃ§o 67,Rio de Janeiro,RJ,05454-876,Brazil
3,VICTE,3,1996-07-08 00:00:00,1996-08-05 00:00:00,1996-07-15,1,41.34,Victuailles en stock,2 rue du Commerce,Lyon,NaN,69004,France
4,SUPRD,4,1996-07-09 00:00:00,1996-08-06 00:00:00,1996-07-11,2,51.30,SuprÃªmes dÃ©lices,Boulevard Tirou 255,Charleroi,NaN,B-6000,Belgium
5,HANAR,3,1996-07-10 00:00:00,1996-07-24 00:00:00,1996-07-16,2,58.17,Hanari Carnes,Rua do PaÃ§o 67,Rio de Janeiro,RJ,05454-876,Brazil
...,...,...,...,...,...,...,...,...,...,...,...,...,...
833,PERIC,2,35920,35948,NaT,2,24.95,Pericles Comidas clÃ¡sicas,Calle Dr. Jorge Cash 321,MÃ©xico D.F.,NaN,5033,Mexico
834,SIMOB,7,35921,35949,NaT,2,18.44,Simons bistro,VinbÃ¦ltet 34,Kobenhavn,NaN,1734,Denmark
835,RICSU,8,35921,35949,NaT,2,6.19,Richter Supermarkt,Starenweg 5,GenÃ¨ve,NaN,1204,Switzerland
836,BONAP,4,35921,35949,NaT,2,38.28,Bon app',12 rue des Bouchers,Marseille,NaN,13008,France
837,RATTC,1,35921,35949,NaT,2,8.53,Rattlesnake Canyon Grocery,2817 Milton Dr.,Albuquerque,NM,87110,USA

In [47]:
df = df.drop("customerID", axis=1)

In [48]:
df.head()

,employeeID,orderDate,requiredDate,shippedDate,shipVia,freight,shipName,shipAddress,shipCity,shipRegion,shipPostalCode,shipCountry
1,6,1996-07-05 00:00:00,1996-08-16 00:00:00,1996-07-10,1,11.61,Toms SpezialitÃ¤ten,Luisenstr. 48,MÃ¼nster,NaN,44087,Germany
2,4,1996-07-08 00:00:00,1996-08-05 00:00:00,1996-07-12,2,65.83,Hanari Carnes,Rua do PaÃ§o 67,Rio de Janeiro,RJ,05454-876,Brazil
3,3,1996-07-08 00:00:00,1996-08-05 00:00:00,1996-07-15,1,41.34,Victuailles en stock,2 rue du Commerce,Lyon,NaN,69004,France
4,4,1996-07-09 00:00:00,1996-08-06 00:00:00,1996-07-11,2,51.30,SuprÃªmes dÃ©lices,Boulevard Tirou 255,Charleroi,NaN,B-6000,Belgium
5,3,1996-07-10 00:00:00,1996-07-24 00:00:00,1996-07-16,2,58.17,Hanari Carnes,Rua do PaÃ§o 67,Rio de Janeiro,RJ,05454-876,Brazil

In [50]:
df.isnull().sum()

employeeID          0
orderDate           0
requiredDate        0
shippedDate        29
shipVia             0
freight             0
shipName            0
shipAddress         0
shipCity            0
shipRegion        512
shipPostalCode     19
shipCountry         0
dtype: int64

In [51]:
df.isnull().sum().sum()

560

In [53]:
df.duplicated().sum()

0

In [56]:
df["shippedDate"].isnull().sum()

29

In [58]:
df["shippedDate"].mode

<bound method Series.mode of 1     1996-07-10
2     1996-07-12
3     1996-07-15
4     1996-07-11
5     1996-07-16
         ...
833          NaT
834          NaT
835          NaT
836          NaT
837          NaT
Name: shippedDate, Length: 837, dtype: datetime64[ns]>

In [61]:
df["shippedDate"]= df["shippedDate"].fillna("1997-12-30")

In [62]:
df["shippedDate"]

1     1996-07-10
2     1996-07-12
3     1996-07-15
4     1996-07-11
5     1996-07-16
         ...
833   1997-12-30
834   1997-12-30
835   1997-12-30
836   1997-12-30
837   1997-12-30
Name: shippedDate, Length: 837, dtype: datetime64[ns]

In [63]:
data = [10, 20, 30, 40, 50]
series = pd.Series(data, index=['a', 'b', 'c', 'd', 'e'])
print(series)

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [64]:
data_dict = {'A': 100, 'B': 200, 'C': 300}
series_dict = pd.Series(data_dict)
print(series_dict)

A    100
B    200
C    300
dtype: int64

In [67]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana'],
    'Age': [25, 30, 35, 28],
    'City': ['New York', 'London', 'Tokyo', 'Paris'],
    'Salary': [70000, 80000, 90000, 75000]
}
df = pd.DataFrame(data)
print(df)

      Name  Age      City  Salary
0    Alice   25  New York   70000
1      Bob   30    London   80000
2  Charlie   35     Tokyo   90000
3    Diana   28     Paris   75000

In [68]:
data_list = [['Alice', 25, 70000], ['Bob', 30, 80000]]

df_list = pd.DataFrame(data_list, columns=['Name', 'Age', 'Salary'])
print(df_list)

    Name  Age  Salary
0  Alice   25   70000
1    Bob   30   80000

In [72]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 838 entries, 0 to 837
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   orderID         838 non-null    int64
 1   customerID      838 non-null    object
 2   employeeID      838 non-null    int64
 3   orderDate       838 non-null    object
 4   requiredDate    838 non-null    object
 5   shippedDate     809 non-null    datetime64[ns]
 6   shipVia         838 non-null    int64
 7   freight         838 non-null    float64
 8   shipName        838 non-null    object
 9   shipAddress     838 non-null    object
 10  shipCity        838 non-null    object
 11  shipRegion      325 non-null    object
 12  shipPostalCode  819 non-null    object
 13  shipCountry     838 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(3), object(9)
memory usage: 91.8+ KB

In [75]:
df.index

RangeIndex(start=0, stop=838, step=1)

In [77]:
import numpy as np
np.random.seed(42)
df = pd.DataFrame({
    'A': np.random.randn(100),
    'B': np.random.randint(1, 10, 100),
    'C': np.random.choice(['X', 'Y', 'Z'], 100),
    'D': pd.date_range('2023-01-01', periods=100, freq='D'),
    'E': np.random.randn(100) * 100
})

In [78]:
df.head()

          A  B  C          D           E
0  0.496714  9  Y 2023-01-01   23.229616
1 -0.138264  5  Y 2023-01-02   17.618092
2  0.647689  1  Y 2023-01-03 -115.256537
3  1.523030  3  Y 2023-01-04 -150.076839
4 -0.234153  8  Z 2023-01-05   16.502280

In [79]:
# Individual statistics
print(df['A'].mean())       # Mean

print(df['A'].median())     # Median

print(df['A'].mode())       # Mode

print(df['A'].std())        # Standard deviation

print(df['A'].var())        # Variance

print(df['A'].min())        # Minimum

print(df['A'].max())        # Maximum

print(df['A'].quantile(0.25))  # 25th percentile

-0.10384651739409384
-0.1269562917797126
0    -2.619745
1    -1.987569
2    -1.959670
3    -1.913280
4    -1.763040
        ...
95    1.523030
96    1.538037
97    1.564644
98    1.579213
99    1.852278
Name: A, Length: 100, dtype: float64
0.9081684280078008
0.8247698936301602
-2.6197451040897444
1.8522781845089378
-0.6009056704964529

In [80]:
print(df['A'].quantile(0.25))  # 25th percentile

-0.6009056704964529

In [81]:
print(df['C'].value_counts())    # Count of unique values

C
X    36
Y    35
Z    29
Name: count, dtype: int64

In [82]:
print(df['C'].nunique())         # Number of unique values

3

In [83]:
print(df.notnull().sum())        # Count of non-missing values

A    100
B    100
C    100
D    100
E    100
dtype: int64

In [87]:
df1.head()

,orderID,customerID,employeeID,orderDate,requiredDate,shippedDate,shipVia,freight,shipName,shipAddress,shipCity,shipRegion,shipPostalCode,shipCountry
0,10248,VINET,5,1996-07-04 00:00:00,1996-08-01 00:00:00,1996-07-16,3,32.38,Vins et alcools Chevalier,59 rue de l'Abbaye,Reims,NaN,51100,France
1,10249,TOMSP,6,1996-07-05 00:00:00,1996-08-16 00:00:00,1996-07-10,1,11.61,Toms SpezialitÃ¤ten,Luisenstr. 48,MÃ¼nster,NaN,44087,Germany
2,10250,HANAR,4,1996-07-08 00:00:00,1996-08-05 00:00:00,1996-07-12,2,65.83,Hanari Carnes,Rua do PaÃ§o 67,Rio de Janeiro,RJ,05454-876,Brazil
3,10251,VICTE,3,1996-07-08 00:00:00,1996-08-05 00:00:00,1996-07-15,1,41.34,Victuailles en stock,2 rue du Commerce,Lyon,NaN,69004,France
4,10252,SUPRD,4,1996-07-09 00:00:00,1996-08-06 00:00:00,1996-07-11,2,51.30,SuprÃªmes dÃ©lices,Boulevard Tirou 255,Charleroi,NaN,B-6000,Belgium

In [96]:
df.loc[20:40:4, ["shipVia","customerID",  "shipCity"]]

    shipVia customerID        shipCity
20        3      GROSR         Caracas
24        2      RATTC     Albuquerque
28        3      TORTU    MÃ©xico D.F.
32        1      BERGS          LuleÃ¥
36        1      LEHMS  Frankfurt a.M.
40        1      REGGC   Reggio Emilia

In [101]:
df.iloc[10:100:10,2:7]

    employeeID            orderDate         requiredDate shippedDate  shipVia
10           1  1996-07-17 00:00:00  1996-08-14 00:00:00  1996-07-23        1
20           8  1996-07-30 00:00:00  1996-08-27 00:00:00  1996-08-02        3
30           8  1996-08-12 00:00:00  1996-09-09 00:00:00  1996-08-16        2
40           4  1996-08-23 00:00:00  1996-09-20 00:00:00  1996-09-03        1
50           6  1996-09-05 00:00:00  1996-10-03 00:00:00  1996-09-11        2
60           7  1996-09-18 00:00:00  1996-10-16 00:00:00  1996-09-24        3
70           8  1996-10-01 00:00:00  1996-10-29 00:00:00  1996-10-04        2
80           4  1996-10-14 00:00:00  1996-11-11 00:00:00  1996-10-17        3
90           4  1996-10-25 00:00:00  1996-11-22 00:00:00  1996-10-29        3

In [102]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve'],
    'Age': [25, 30, 35, 28, 32],
    'Department': ['HR', 'IT', 'Finance', 'HR', 'IT'],
    'Salary': [70000, 80000, 90000, 75000, 85000]
}
df = pd.DataFrame(data, index=['emp1', 'emp2', 'emp3', 'emp4', 'emp5'])

In [103]:
df

         Name  Age Department  Salary
emp1    Alice   25         HR   70000
emp2      Bob   30         IT   80000
emp3  Charlie   35    Finance   90000
emp4    Diana   28         HR   75000
emp5      Eve   32         IT   85000

In [109]:
df[df['Age'] > 30]

         Name  Age Department  Salary
emp3  Charlie   35    Finance   90000
emp5      Eve   32         IT   85000

In [106]:
mask

emp1    False
emp2    False
emp3     True
emp4    False
emp5     True
Name: Age, dtype: bool

In [112]:
df[(df['Age'] > 25) & (df['Department'] == 'IT')]   # and

     Name  Age Department  Salary
emp2  Bob   30         IT   80000
emp5  Eve   32         IT   85000

In [113]:
df[(df['Age'] > 25) | (df['Department'] == 'IT')]   # or

         Name  Age Department  Salary
emp2      Bob   30         IT   80000
emp3  Charlie   35    Finance   90000
emp4    Diana   28         HR   75000
emp5      Eve   32         IT   85000

In [114]:
departments = ['HR', 'Finance']

print(df[df['Department'].isin(departments)])

         Name  Age Department  Salary
emp1    Alice   25         HR   70000
emp3  Charlie   35    Finance   90000
emp4    Diana   28         HR   75000

In [116]:
df[df['Name'].str.contains('C')]    # Names containing 'A'

         Name  Age Department  Salary
emp3  Charlie   35    Finance   90000

In [117]:
print(df.query('Age > 30'))

         Name  Age Department  Salary
emp3  Charlie   35    Finance   90000
emp5      Eve   32         IT   85000

In [118]:
print(df.query('Age > 30 and Department == "IT"'))

     Name  Age Department  Salary
emp5  Eve   32         IT   85000