In [2]:
import pandas as pd

In [3]:
df_str = pd.DataFrame({
    'names': ['  Alice  ', 'BOB', 'charlie', 'DIANA'],
    'emails': ['alice@email.com', 'bob@COMPANY.COM', 'charlie@email.com', 'diana@company.com']
})

In [4]:
df_str

       names             emails
0    Alice      alice@email.com
1        BOB    bob@COMPANY.COM
2    charlie  charlie@email.com
3      DIANA  diana@company.com

In [5]:
# String methods (vectorized operations)
print(df_str['names'].str.lower())       # Convert to lowercase

0      alice
1          bob
2      charlie
3        diana
Name: names, dtype: object

In [6]:
print(df_str['names'].str.upper())       # Convert to uppercase

0      ALICE
1          BOB
2      CHARLIE
3        DIANA
Name: names, dtype: object

In [7]:
print(df_str['names'].str.title())       # Title case

0      Alice
1          Bob
2      Charlie
3        Diana
Name: names, dtype: object

In [8]:
print(df_str['names'].str.strip())       # Remove leading/trailing whitespace

0      Alice
1        BOB
2    charlie
3      DIANA
Name: names, dtype: object

In [9]:
print(df_str['names'].str.len())         # Length of strings

0    9
1    3
2    7
3    5
Name: names, dtype: int64

In [10]:
print(df_str['names'].str.replace(' ', '_'))   # Replace characters
print(df_str['emails'].str.split('@'))          # Split strings

0    __Alice__
1          BOB
2      charlie
3        DIANA
Name: names, dtype: object
0      [alice, email.com]
1      [bob, COMPANY.COM]
2    [charlie, email.com]
3    [diana, company.com]
Name: emails, dtype: object

In [11]:
print(df_str['emails'].str.split('@', expand=True))  # Split into columns

         0            1
0    alice    email.com
1      bob  COMPANY.COM
2  charlie    email.com
3    diana  company.com

In [12]:
df_dup = pd.DataFrame({
    'A': [1, 2, 2, 3, 3, 3],
    'B': ['x', 'y', 'y', 'z', 'z', 'w'],
    'C': [10, 20, 20, 30, 30, 40]
})

In [13]:
df_dup

   A  B   C
0  1  x  10
1  2  y  20
2  2  y  20
3  3  z  30
4  3  z  30
5  3  w  40

In [14]:
df_dup.duplicated().sum()

2

In [15]:
df_dup.drop_duplicates()

   A  B   C
0  1  x  10
1  2  y  20
3  3  z  30
5  3  w  40

In [16]:
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'Salary': [70000, 80000, 90000]
})

In [17]:
df

      Name  Age  Salary
0    Alice   25   70000
1      Bob   30   80000
2  Charlie   35   90000

In [18]:
df["newcol"] = "Null"

In [19]:
df

      Name  Age  Salary newcol
0    Alice   25   70000   Null
1      Bob   30   80000   Null
2  Charlie   35   90000   Null

In [20]:
df['Bonus'] = df['Salary'] * 0.1

In [21]:
df

      Name  Age  Salary newcol   Bonus
0    Alice   25   70000   Null  7000.0
1      Bob   30   80000   Null  8000.0
2  Charlie   35   90000   Null  9000.0

In [23]:
df.drop("newcol", axis = 1, inplace=True)

In [24]:
df

      Name  Age  Salary   Bonus
0    Alice   25   70000  7000.0
1      Bob   30   80000  8000.0
2  Charlie   35   90000  9000.0

In [25]:
df['Full_Info'] = df['Name'] + ' (' + df['Age'].astype(str) + ')'

In [26]:
df

      Name  Age  Salary   Bonus     Full_Info
0    Alice   25   70000  7000.0    Alice (25)
1      Bob   30   80000  8000.0      Bob (30)
2  Charlie   35   90000  9000.0  Charlie (35)

In [27]:
df = df.assign(
    Tax = df['Salary'] * 0.3,
    Net_Salary = lambda x: x['Salary'] - x['Tax']
)

In [28]:
df

      Name  Age  Salary   Bonus     Full_Info      Tax  Net_Salary
0    Alice   25   70000  7000.0    Alice (25)  21000.0     49000.0
1      Bob   30   80000  8000.0      Bob (30)  24000.0     56000.0
2  Charlie   35   90000  9000.0  Charlie (35)  27000.0     63000.0

In [29]:
df.insert(0, 'Employee_ID', ['E001', 'E002', 'E003'])

In [30]:
df

  Employee_ID     Name  Age  Salary   Bonus     Full_Info      Tax  Net_Salary
0        E001    Alice   25   70000  7000.0    Alice (25)  21000.0     49000.0
1        E002      Bob   30   80000  8000.0      Bob (30)  24000.0     56000.0
2        E003  Charlie   35   90000  9000.0  Charlie (35)  27000.0     63000.0

In [31]:
df.insert(3, 'Employee_ID1', ['E001', 'E002', 'E003'])

In [32]:
df

,Employee_ID,Name,Age,Employee_ID1,Salary,Bonus,Full_Info,Tax,Net_Salary
0,E001,Alice,25,E001,70000,7000.0,Alice (25),21000.0,49000.0
1,E002,Bob,30,E002,80000,8000.0,Bob (30),24000.0,56000.0
2,E003,Charlie,35,E003,90000,9000.0,Charlie (35),27000.0,63000.0

In [33]:
df_renamed = df.rename(columns={'Name': 'Employee_Name', 'Age': 'Employee_Age'})

In [34]:
df_renamed

,Employee_ID,Employee_Name,Employee_Age,Employee_ID1,Salary,Bonus,Full_Info,Tax,Net_Salary
0,E001,Alice,25,E001,70000,7000.0,Alice (25),21000.0,49000.0
1,E002,Bob,30,E002,80000,8000.0,Bob (30),24000.0,56000.0
2,E003,Charlie,35,E003,90000,9000.0,Charlie (35),27000.0,63000.0

In [35]:
df_sort = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana'],
    'Age': [25, 35, 30, 28],
    'Salary': [70000, 90000, 80000, 75000],
    'Department': ['HR', 'IT', 'Finance', 'HR']
})

In [36]:
df_sort

      Name  Age  Salary Department
0    Alice   25   70000         HR
1      Bob   35   90000         IT
2  Charlie   30   80000    Finance
3    Diana   28   75000         HR

In [38]:
print(df_sort.sort_values('Age', ascending=False))

      Name  Age  Salary Department
1      Bob   35   90000         IT
2  Charlie   30   80000    Finance
3    Diana   28   75000         HR
0    Alice   25   70000         HR

In [39]:
print(df_sort.sort_values('Name', ascending=False))

      Name  Age  Salary Department
3    Diana   28   75000         HR
2  Charlie   30   80000    Finance
1      Bob   35   90000         IT
0    Alice   25   70000         HR

In [42]:
df_sales = pd.DataFrame({
    'Region': ['North', 'South', 'East', 'West', 'North', 'South', 'East', 'West'],
    'Product': ['A', 'A', 'B', 'B', 'A', 'B', 'A', 'B'],
    'Sales': [100, 150, 200, 120, 180, 160, 140, 190],
    'Profit': [20, 30, 40, 25, 35, 32, 28, 38],
    'Quarter': ['Q1', 'Q3', 'Q1', 'Q1', 'Q2', 'Q3', 'Q2', 'Q2']
})

In [43]:
df_sales

  Region Product  Sales  Profit Quarter
0  North       A    100      20      Q1
1  South       A    150      30      Q3
2   East       B    200      40      Q1
3   West       B    120      25      Q1
4  North       A    180      35      Q2
5  South       B    160      32      Q3
6   East       A    140      28      Q2
7   West       B    190      38      Q2

In [44]:
grouped = df_sales.groupby('Region')

In [46]:
list(grouped)

[('East',
    Region Product  Sales  Profit Quarter
  2   East       B    200      40      Q1
  6   East       A    140      28      Q2),
 ('North',
    Region Product  Sales  Profit Quarter
  0  North       A    100      20      Q1
  4  North       A    180      35      Q2),
 ('South',
    Region Product  Sales  Profit Quarter
  1  South       A    150      30      Q3
  5  South       B    160      32      Q3),
 ('West',
    Region Product  Sales  Profit Quarter
  3   West       B    120      25      Q1
  7   West       B    190      38      Q2)]

In [47]:
print(grouped.sum())

       Product  Sales  Profit Quarter
Region
East        BA    340      68    Q1Q2
North       AA    280      55    Q1Q2
South       AB    310      62    Q3Q3
West        BB    310      63    Q1Q2

In [48]:
print(grouped.count())

        Product  Sales  Profit  Quarter
Region
East          2      2       2        2
North         2      2       2        2
South         2      2       2        2
West          2      2       2        2

In [49]:
multi_grouped = df_sales.groupby(['Region', 'Product'])

In [50]:
print(multi_grouped.sum())

                Sales  Profit Quarter
Region Product
East   A          140      28      Q2
       B          200      40      Q1
North  A          280      55    Q1Q2
South  A          150      30      Q3
       B          160      32      Q3
West   B          310      63    Q1Q2

In [51]:
print(df_sales.groupby('Region')['Sales'].sum())

Region
East     340
North    280
South    310
West     310
Name: Sales, dtype: int64

In [96]:
print(df_sales.groupby('Product')[['Sales', "Profit"]].sum())

         Sales  Profit
Product
A          570     113
B          670     135

In [56]:
df_sales

  Region Product  Sales  Profit Quarter
0  North       A    100      20      Q1
1  South       A    150      30      Q3
2   East       B    200      40      Q1
3   West       B    120      25      Q1
4  North       A    180      35      Q2
5  South       B    160      32      Q3
6   East       A    140      28      Q2
7   West       B    190      38      Q2

In [57]:
pivot_table = pd.pivot_table(df_sales, 
                           values='Sales', 
                           index='Region', 
                           columns='Product', 
                           aggfunc='sum',
                           fill_value=0)

In [58]:
pivot_table

Product    A    B
Region
East     140  200
North    280    0
South    150  160
West       0  310

In [59]:
pivot_table = pd.pivot_table(df_sales, 
                           values='Sales', 
                           index='Region', 
                           columns='Quarter', 
                           aggfunc='sum',
                           fill_value=0)

In [60]:
pivot_table

Quarter   Q1   Q2   Q3
Region
East     200  140    0
North    100  180    0
South      0    0  310
West     120  190    0

In [63]:
pivot_table = pd.pivot_table(df_sales, 
                           values='Profit', 
                           index='Product', 
                           columns='Quarter', 
                           aggfunc='sum',
                           fill_value=0)

In [64]:
pivot_table

Quarter  Q1  Q2  Q3
Product
A        20  63  30
B        65  38  32

In [65]:
df1 = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
df2 = pd.DataFrame({'A': [7, 8, 9], 'B': [10, 11, 12]})
df3 = pd.DataFrame({'C': [13, 14, 15], 'D': [16, 17, 18]})

In [66]:
df1

   A  B
0  1  4
1  2  5
2  3  6

In [67]:
df2

   A   B
0  7  10
1  8  11
2  9  12

In [68]:
df3

    C   D
0  13  16
1  14  17
2  15  18

In [69]:
result_vertical = pd.concat([df1, df2])
print(result_vertical)

   A   B
0  1   4
1  2   5
2  3   6
0  7  10
1  8  11
2  9  12

In [70]:
result_horizontal = pd.concat([df1, df3], axis=1)
print(result_horizontal)

   A  B   C   D
0  1  4  13  16
1  2  5  14  17
2  3  6  15  18

In [72]:
result_reindex = pd.concat([df1, df2], ignore_index=True)
print(result_reindex)

   A   B
0  1   4
1  2   5
2  3   6
3  7  10
4  8  11
5  9  12

In [74]:
import numpy as np

In [75]:
date_range = pd.date_range('2023-01-01', periods=100, freq='D')
ts_data = pd.DataFrame({
    'date': date_range,
    'value': np.random.randn(100).cumsum(),
    'category': np.random.choice(['A', 'B', 'C'], 100)
})

In [76]:
date_range

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12',
               '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16',
               '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20',
               '2023-01-21', '2023-01-22', '2023-01-23', '2023-01-24',
               '2023-01-25', '2023-01-26', '2023-01-27', '2023-01-28',
               '2023-01-29', '2023-01-30', '2023-01-31', '2023-02-01',
               '2023-02-02', '2023-02-03', '2023-02-04', '2023-02-05',
               '2023-02-06', '2023-02-07', '2023-02-08', '2023-02-09',
               '2023-02-10', '2023-02-11', '2023-02-12', '2023-02-13',
               '2023-02-14', '2023-02-15', '2023-02-16', '2023-02-17',
               '2023-02-18', '2023-02-19', '2023-02-20', '2023-02-21',
               '2023-02-22', '2023-02-23', '2023-02-24', '2023-02-25',
               '2023-02-26', '2023-02-27', '2023-02-28', '2023-03-01',
               '2023-03-02', '2023-03-03', '2023-03-04', '2023-03-05',
               '2023-03-06', '2023-03-07', '2023-03-08', '2023-03-09',
               '2023-03-10', '2023-03-11', '2023-03-12', '2023-03-13',
               '2023-03-14', '2023-03-15', '2023-03-16', '2023-03-17',
               '2023-03-18', '2023-03-19', '2023-03-20', '2023-03-21',
               '2023-03-22', '2023-03-23', '2023-03-24', '2023-03-25',
               '2023-03-26', '2023-03-27', '2023-03-28', '2023-03-29',
               '2023-03-30', '2023-03-31', '2023-04-01', '2023-04-02',
               '2023-04-03', '2023-04-04', '2023-04-05', '2023-04-06',
               '2023-04-07', '2023-04-08', '2023-04-09', '2023-04-10'],
              dtype='datetime64[ns]', freq='D')

In [77]:
ts_data

         date     value category
0  2023-01-01  1.096192        B
1  2023-01-02  0.063780        C
2  2023-01-03 -1.380983        C
3  2023-01-04 -0.567763        B
4  2023-01-05 -1.005504        A
..        ...       ...      ...
95 2023-04-06 -9.464976        C
96 2023-04-07 -8.145877        A
97 2023-04-08 -7.084195        C
98 2023-04-09 -7.203496        B
99 2023-04-10 -6.633168        A

[100 rows x 3 columns]

In [78]:
ts_data.dtypes

date        datetime64[ns]
value              float64
category            object
dtype: object

In [79]:
ts_data['date'] = pd.to_datetime(ts_data['date'])

In [80]:
ts_data

         date     value category
0  2023-01-01  1.096192        B
1  2023-01-02  0.063780        C
2  2023-01-03 -1.380983        C
3  2023-01-04 -0.567763        B
4  2023-01-05 -1.005504        A
..        ...       ...      ...
95 2023-04-06 -9.464976        C
96 2023-04-07 -8.145877        A
97 2023-04-08 -7.084195        C
98 2023-04-09 -7.203496        B
99 2023-04-10 -6.633168        A

[100 rows x 3 columns]

In [81]:
ts_data.dtypes

date        datetime64[ns]
value              float64
category            object
dtype: object

In [82]:
ts_data = ts_data.set_index('date')

In [83]:
ts_data

               value category
date
2023-01-01  1.096192        B
2023-01-02  0.063780        C
2023-01-03 -1.380983        C
2023-01-04 -0.567763        B
2023-01-05 -1.005504        A
...              ...      ...
2023-04-06 -9.464976        C
2023-04-07 -8.145877        A
2023-04-08 -7.084195        C
2023-04-09 -7.203496        B
2023-04-10 -6.633168        A

[100 rows x 2 columns]

In [85]:
df_sales.set_index("Quarter")

        Region Product  Sales  Profit
Quarter
Q1       North       A    100      20
Q3       South       A    150      30
Q1        East       B    200      40
Q1        West       B    120      25
Q2       North       A    180      35
Q3       South       B    160      32
Q2        East       A    140      28
Q2        West       B    190      38

In [86]:
ts_data['year'] = ts_data.index.year

In [87]:
ts_data

               value category  year
date
2023-01-01  1.096192        B  2023
2023-01-02  0.063780        C  2023
2023-01-03 -1.380983        C  2023
2023-01-04 -0.567763        B  2023
2023-01-05 -1.005504        A  2023
...              ...      ...   ...
2023-04-06 -9.464976        C  2023
2023-04-07 -8.145877        A  2023
2023-04-08 -7.084195        C  2023
2023-04-09 -7.203496        B  2023
2023-04-10 -6.633168        A  2023

[100 rows x 3 columns]

In [88]:
ts_data['month'] = ts_data.index.month

In [89]:
ts_data['day'] = ts_data.index.day

In [90]:
ts_data['weekday'] = ts_data.index.dayofweek

In [91]:
ts_data['quarter'] = ts_data.index.quarter

In [92]:
ts_data

               value category  year  month  day  weekday  quarter
date
2023-01-01  1.096192        B  2023      1    1        6        1
2023-01-02  0.063780        C  2023      1    2        0        1
2023-01-03 -1.380983        C  2023      1    3        1        1
2023-01-04 -0.567763        B  2023      1    4        2        1
2023-01-05 -1.005504        A  2023      1    5        3        1
...              ...      ...   ...    ...  ...      ...      ...
2023-04-06 -9.464976        C  2023      4    6        3        2
2023-04-07 -8.145877        A  2023      4    7        4        2
2023-04-08 -7.084195        C  2023      4    8        5        2
2023-04-09 -7.203496        B  2023      4    9        6        2
2023-04-10 -6.633168        A  2023      4   10        0        2

[100 rows x 7 columns]